### ISSUE TITLE
re: Habitica SyntaxError

### ISSUE THREAD

**Issue by Quenz** [matryer/bitbar-plugins#1119]
FAO: (@SCdF)

This error.

<img width="434" alt="screen shot 2018-11-01 at 6 52 47 pm" src="https://user-images.githubusercontent.com/17078658/47839592-5b23a480-de07-11e8-973e-81495ee17015.png">

I have added my user ID and API token.

**Comment by SCdF** [comment]
Hi @Quenz, what version of node is the script using?

You can find out by typing `/usr/local/bin/node --version` into a terminal:

```bash
scdf at SCdF in ~/Code/SCdF/bitbar-plugins on master▲
$ /usr/local/bin/node --version
v11.0.0
```

**Comment by Quenz** [comment]
@SCdF I get 

> v4.5.0

**Comment by SCdF** [comment]
@Quenz unfortunately that version of Node is a couple of years old, and was only just starting to get support for ES6 (certain language features in Javascript that are used in that script).

You want at least the latest version of Node 6, but ideally as recent as you can go.

Do you know how to installed Node? If it was via `brew`, you should be able to run `brew upgrade` to upgrade all outdated packages (there are probably more specific commands if you want to just upgrade node).

**Comment by Quenz** [comment]
@SCdF I honestly don't remember ever installing Node. I'm not really a developer. I installed it via brew just now and it installed it in `/usr/local/Cellar/node/11.0.0` so my issue persists.

**Comment by SCdF** [comment]
Sorry about this! It should have created a symlink, so that `/usr/local/bin/node` points to the version that brew installed. Unfortunately that commonly fails with an error that looks like this:
```
Warning: Could not link node. Unlinking...
Error: The `brew link` step did not complete successfully
```

If you don't remember if you saw this, you can run `brew link node` and it will attempt to link it again.

If the linking is the problem then it's a permissions error, and you should run `cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var opt Cellar Caskroom Frameworks.`. This looks like it's doing a lot, but it's really just going to your `local` directory, and making sure you (`$(whoami)`) owns everything under those directories, which in turn means you're allowed to create symlinks there.

Once you've run that try `brew link node` again and let me know how it goers.

**Comment by Quenz** [comment]
Don't be sorry, I'm happy you're helping me!

Here's what I got running `brew link node`

```
Ms-MacBook-Pro:BitBar plugins M$ brew link node
Linking /usr/local/Cellar/node/11.0.0... 
Error: Could not symlink bin/node
Target /usr/local/bin/node
already exists. You may want to remove it:
  rm '/usr/local/bin/node'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node
```

It looks like a different error, and suggests something different to what you just suggested, I'm not sure what to do.

**Comment by SCdF** [comment]
So I'd expect that there would already be one there, though I don't know where it came from.

My first suggestion would be do to `ls -l /usr/local/bin/node` which will show you where it's coming from:

```
$ ls -l /usr/local/bin/node
lrwxr-xr-x  1 scdf  admin  30 24 Oct 18:06 /usr/local/bin/node -> ../Cellar/node/11.0.0/bin/node
```

If it's not a symlink (e.g. it doesn't have the arrow pointing somewhere else), then I'm guessing you installed it at some point via Node itself (as opposed to using brew as a package manager). In which case, you might as well [use the node installer again](https://nodejs.org/en/) instead of using brew :-)

If it's a symlink somewhere else I'd be interested to know where.

**Comment by Quenz** [comment]
```
$ ls -l /usr/local/bin/node
-rwxrwxr-x  1 root  wheel  23599232 Aug 17  2016 /usr/local/bin/node
```

I don't ever remember installing it from the Node website, I don't remember where it came from. Does BitBar automatically install it?

Installing the LTS Node from the website fixed it, so thanks so much!
