### ISSUE TITLE
re: Stock Ticker

### ISSUE THREAD

**Issue by sandiegoscott** [matryer/bitbar-plugins#1265]
FAO: (@rkanter)

I'm getting an error installing the Stock Ticker plug-in:

`File "/Users/scott/BitBar Plugins/stock-ticker.30s.py", line 26, in <module>
    response = urllib2.urlopen("https://cloud.iexapis.com/stable/stock/market/batch?symbols=" + ','.join(stock_symbols) + "&types=quote&filter=symbol,latestPrice,change,changePercent&displayPercent=true&token=" + api_token)`

Could `cloud.iexapis.com` now be located at `iexcloud.io/apis` or something similar?

Scott

**Comment by gingerbeardman** [comment]
Dupe #1261

**Comment by rkanter** [comment]
@sandiegoscott no, cloud.iexapis.com is the correct url (as per https://iexcloud.io/docs/api/).  The old url was at https://api.iextrading.com (see the pull request where I replaced the old BitBar plugin #1251.

It's hard to say if this is the same issue as #1261 because #1261 doesn't provide any details...

Anyway, did you make sure to get an API Token following the steps in the file?

**Comment by sandiegoscott** [comment]
This is solved in #1261. I wasn't aware that I had to look in the code to find further instructions. Nowhere did I see directions to do that. This plug-in is not for everyone if you have to make changes to the code.

**Comment by gingerbeardman** [comment]
@sandiegoscott a large number of bitbar plugins require configuration by the user. It's a good idea for us to make this clearer somehow

**Comment by rkanter** [comment]
+1 to making that more clear in general.

I actually thought about making it check if you hadn't set the api token and give a better message (e.g. "The script requires configuration") instead of a python error, but I looked at a bunch of the other plugins and none of them did that so I didn't bother.  Maybe I'll go and do that anyway and start a trend :)
