### ISSUE TITLE
re: Twitch Following

### ISSUE THREAD

**Issue by fenhl** [matryer/bitbar-plugins#1308]
FAO: (@SCdF)

Twitch is shutting down their kraken API and the endpoint used in this plugin has started to return 410 Gone. The new helix API has no equivalent endpoint, so it needs to be replaced by a call to [Get Users Follows](https://dev.twitch.tv/docs/api/reference/#get-users-follows) followed by a call to [Get Streams](https://dev.twitch.tv/docs/api/reference/#get-streams) with the returned user IDs.

**Comment by SCdF** [comment]
Hey @fenhl, yeah, I figured this was coming, they've been sabre-rattling over it for awhile.

I've changed computers since I built this so I don't use MacOS much anymore. I also think the way I did auth has to change as well?

It sounds like you know what you're doing, did you want to take a crack at it? Otherwise IDK when I'll be able to find the time unfortunately :-(

**Comment by fenhl** [comment]
I'm writing an updated plugin, but it will be out of tree since I'm writing it in Rust. Will link here once it's up.

**Comment by fenhl** [comment]
The new plugin is at <https://github.com/fenhl/bitbar-twitch>. It's based on modifications I'd made to this one for myself and I'm sure there are a few things that could be improved to make it more useful for others, so feel free to open issues for feature requests.
