### ISSUE TITLE
Head to head: The best Pomodoro plugin

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar-plugins#180]
We need to select between these two excellent Pomodoro plugins:

  * https://github.com/matryer/bitbar-plugins/pull/177
  * https://github.com/matryer/bitbar-plugins/pull/178

We only want one in the repo - but which one? We'll let the community decide.

**Comment by keithamus** [comment]
#178:
 - + Emoji
 - + Notifications
 - + Configurable
 - - Writes multiple files
 - - Needs shellcheck changes

#177:
 - + Code more readable
 - + Shellchecked (now)
 - + Original

**Comment by manojlds** [comment]
#178 :+1:

**Comment by gorangajic** [comment]
I have searched plugins for pomodoro but forget to look up in pull requests :smile: what are the changes that 2 people are working on the same thing in the same time ? 

Imo we should merge both plugins because functionality is a bit different #178 have two timers(work and break) that switch automatically, and #177 have just one timer that need to be restarted manually 

also #178 play a sound when timer reach 00:00

> Writes multiple files

I can move that in one file but wanted to keep things more simpler
 
btw #177 have bug, config files should be moved from plugin directory because bitbar treat that file like a new plugin so there is new warning icon ⚠️ 

no hard feelings, whatever you guys decide :smile:

**Comment by matryer** [comment]
What's funny is - a friend of mine has started work on a Pomodoro plugin too - I've sent him a link to this. :)

**Comment by matryer** [comment]
Shall we spellcheck it and go with #178 then?

**Comment by keithamus** [comment]
Sounds like an idea.

**Comment by sagarjauhari** [comment]
Ahh, found this just when I was about to open a PR for a Pomodoro plugin I wrote too! https://github.com/sagarjauhari/pomodoro.rb/blob/master/pomodoro_bitbar.rb :smile:
