### ISSUE TITLE
re: Last.fm Now Playing

### ISSUE THREAD

**Issue by matthewdias** [matryer/bitbar-plugins#259]
FAO: (@estiens) getting a LoadError on xmlsimple

**Comment by estiens** [comment]
Make sure you have the gem installed for the ruby version that the bitbar app is using (system ruby unless you tell it otherwise)

`gem install xml-simple`

**Comment by matthewdias** [comment]
how can i see/change which ruby version bitbar uses?

**Comment by estiens** [comment]
It uses system ruby by default. I use rbenv to manage ruby versions so my script starts like this

`#!/usr/bin/env /Users/estiens/.rbenv/shims/ruby` instead of `#!/usr/bin/env ruby`

which allows it to use the ruby version I have set for my plugins folder.

If you want to see which version it is using, just make a tiny script that output the version by putting in one line that says `puts RUBY_VERSION`

**Comment by matthewdias** [comment]
thanks got it
