### ISSUE TITLE
re: Brew Services

### ISSUE THREAD

**Issue by deluan** [matryer/bitbar-plugins#452]
FAO: (@eproxus)

The plugin is awesome, but the total number of services doesn't appear when there is any service started and you're not using the dark menu bar. Check this screenshot: http://i.imgur.com/z8tFumr.png

Looks like you're turning off the green color by setting the color to white, which does not work well on the "light" theme

**Comment by eproxus** [comment]
Hi, cool that you're liking it!

I played around with this, and discovered that the ANSI reset is broken in BitBar, where the text turns black instead (which breaks it in a dark menu bar). Solved it by using white instead, which in hindsight wasn't so great. :smile: Didn't actually think of the bright bar.

Is there a solution to this using the dark menu bar functionality somehow (I'm not familiar with it)? Is it a bug in BitBar that reset resets to black (I would argue that it is, since the text is white by default for the dark menu bar).

**Comment by deluan** [comment]
I haven't played with ANSI codes in BitBar yet, but I had a similar problem in my plugin, Checkman Simulator, and what I ended up doing was detecting if dark menu bar is active and use the appropriate color attribute. Something like this:

```
DARK_MODE=`defaults read -g AppleInterfaceStyle 2> /dev/null`.strip
NO_DIM = " color=#{DARK_MODE == 'Dark' ? 'white' : 'black'} "
```

**Comment by deluan** [comment]
Hey @eproxus, I made this change locally, let me know if you want the patch.

**Comment by eproxus** [comment]
You could also just submit a pull request to this repo and take the cred! I want to by no means own this plugin. :-)
