### ISSUE TITLE
re: Transmission Remote

### ISSUE THREAD

**Issue by RowanKaag** [matryer/bitbar-plugins#496]
FAO: (@christophruss)

```
~/Documents/BitBar Plugins > ./transmission.4m.py
∞
---
¶ Limit Speed | refresh=true bash=/usr/bin/python param1=./transmission.4m.py param2=slowdown terminal=false
---
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name | size=12 font=Arial
   4*   99%    2.88 GB  Unknown      0.0     0.0    0.6  Stopped      The Last Witch Hunter 2015 1080p BluRay x264 DTS-JYK | size=12 font=Arial color=yellow refresh=true bash=/usr/bin/python param1=./transmission.4m.py param2=pause param3=4* terminal=false
---
Sum:           4.60 GB              41.0     0.0 | size=12
```

```
$  pip install keyring
Requirement already satisfied (use --upgrade to upgrade): keyring in /usr/local/lib/python2.7/site-packages
```

![Image of Transmission-BitBar](https://s31.postimg.org/8fu136qdn/Screen_Shot_2016_07_23_at_00_46_15.png)

**Comment by tresni** [comment]
Going to take a guess and say you have Homebrew or Macports installed.  The issue is that the PATH set for applications is not the same as the path for your shell...  So `/usr/local/env python` in the shebang is likely hitting system python (where you may not have keyring installed) vs Homebrew/Macports python.

In that case, you can either change the shebang to `/usr/local/bin/python` (for homebrew) or `/opt/local/bin/python` (for Macports iirc.)

Try that and see if it resolves the issue.

**Comment by RowanKaag** [comment]
That did the trick, thank you!
