### ISSUE TITLE
re: Google Finance Stock Ticker

### ISSUE THREAD

**Issue by AyrtonDaSilva** [matryer/bitbar-plugins#622]
FAO: (@jamiesonio)

Hi!

I am trying to add a couple of South African securities on Google Finance as JSE:JSC and JSE:ELI. But I keep getting a syntax error and I don't understand why (no code experience at all).

Thanks in advance for the help!
Ayrton
<img width="418" alt="screen shot 2016-12-12 at 5 16 40 pm" src="https://cloud.githubusercontent.com/assets/24526769/21104320/c917bc08-c08e-11e6-97b6-2fdaaf6a866e.png">

**Comment by tresni** [comment]
I think the issue is your unusual quotes (assuming it's not something weird from your terminal)

```py
stocks={"JSE:JSC", "JSE:ELI"}
```

If you edit the file in textpad, make sure it doesn't replace the double quotes with "smart" quotes.  If you see it change them, just CMD+z and it should revert to plain double quotes.  Or get something like atom.io that is designed around editing text.

**Comment by AyrtonDaSilva** [comment]
Thanks for getting back so quickly! I think it is a problem with text editor or something I did wrong there, I edited it in IDLE and it worked fine!

Thanks so much for the help and the awesome tool!

On Dec 12, 2016, at 8:26 PM, Brian Hartvigsen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the issue is your unusual quotes (assuming it's not something weird from your terminal)

stocks={"JSE:JSC", "JSE:ELI"}

If you edit the file in textpad, make sure it doesn't replace the double quotes with "smart" quotes. If you see it change them, just CMD+z and it should revert to plain double quotes. Or get something like atom.io<http://atom.io> that is designed around editing text.
