### ISSUE TITLE
re: Weather Underground

### ISSUE THREAD

**Issue by peha2407** [matryer/bitbar-plugins#903]
FAO: (@asnodgrass)
Hi Adam
I had just fun with your BitBar plugin. Until I updated to macOS 10.13.1. Now, there are some errors:
"/Applications/BitBar/BitBar_Plugins/Wunderground.30m.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- wunderground (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Applications/BitBar/BitBar_Plugins/Wunderground.30m.rb:3:in `<main>'"
Could you please help me with this? The file 'kernel_require.rb' still exists.
Thanks and regards,
Peter

**Comment by asnodgrass** [comment]
Hello @peha2407, this message indicates that your Ruby installation lacks the `wunderground` gem. Since you upgraded to 10.13, probably the previous installation of the gem was lost.

It looks like you are using the Ruby supplied with OSX; to correct the error, issue `sudo gem install wunderground`. This should install the gem plus any required dependencies.

**Comment by peha2407** [comment]
Hi Adam

Thanks for your answer! You’re right, this was the problem. Now, I have re-installed the gems - it works like a charm!

Regards,
Peter
