### ISSUE TITLE
re: Timezones+

### ISSUE THREAD

**Issue by Shivansh1999** [matryer/bitbar-plugins#934]
FAO: (@aaronedell)How to change timezones?

**Comment by aaronedell** [comment]
Its a bit tacky but you just open the script itself in a test editor, and change the TZ= to whichever timezone you want. You can also add multiple lines so that it cycles through different timezones. You can find the standard list of bash acceptable timezones here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones <https://en.wikipedia.org/wiki/List_of_tz_database_time_zones>
